const base_url = 'https://straat-backend-v3.herokuapp.com';
const graphqlUrl = 'https://straat-backend-v3.herokuapp.com/graphql';
const enter_code_url = '/v4/api/authentication/enterCode';
const verify_postal_url = '/v4/api/utility/postcode';
const signUp_url = '/v4/api/authentication/signup';
const validateInput_url = '/v4/api/authentication/validateInput';
const signIn_url = '/v4/api/authentication/signin';
const feedback_url = '/v4/api/utility/feedback';
const imageUpload_url = '/v4/api/utility/single_file_upload?folderName=profile';
