name: straatinfoflutter
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  graphql: ^3.0.0
  http: ^0.12.1
  flutter_form_builder: ^3.10.1
  provider: ^4.1.3
  flutter_spinkit: ^4.1.2
  random_string: ^2.0.1
  modal_progress_hud: ^0.1.3
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.2+2
  image_picker: ^0.6.7+3
  permission_handler: ^5.0.1+1
  dio: ^3.0.9
  http_parser: ^3.1.4
  device_info: ^0.4.2+4
  intl: ^0.16.1
  speech_bubble: ^0.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

